spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: microservice-config-eureka

eureka:
  instance:
    hostname: eureka01.beautytiger.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false # 禁用自我保护机制*****************
---
server:
  port: 6001
spring:
  profiles: prod
  application:
    name: microservice-config-eureka

eureka:
  instance:
    hostname: eureka01.beautytiger.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true # 开启自我保护机制*****************
