server:
  port: 8000
  servlet:
    context-path: /api/v1/consumer

spring:
  application:
    name: microservice-product-consumer

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: false # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://192.168.28.6:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于microservice-product:8001
    prefer-ip-address: true #访问路径就会显示成IP地址

feign:
  hystrix:
    enabled: true # 开启服务熔断器

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream  # http://localhost:8000/api/v1/consumer/actuator/hystrix.stream
