server:
  port: 7001

spring:
  application:
    name: microservice-zuul

eureka:
  client:
    registerWithEureka: false # 服务注册开关
    fetchRegistry: false # 服务发现开关
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      # 单机版 Eureka 服务注册中心
      defaultZone: http://192.168.28.6:6001/eureka
      # defaultZone: http://eureka01.beautytiger.com:6001/eureka,http://eureka02.beautytiger.com:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true

service:
  microservice-user:
    name: microservice-user
    url: http://localhost:8081

zuul:
  routes:
    product-provider:    # 路由名称，名称任意，路由名称唯一
      path: /api/v1/product/** # 访问路径
      # serviceId: microservice-product # 指定服务ID，会自动从Eureka中找到此服务的ip和端口
      stripPrefix: false # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1
      url: http://localhost:8080
    product-consumer:
      path: /api/v1/consumer/**
      serviceId: microservice-product-consumer
      stripPrefix: false
    product-user:
      path: /api/v1/user/**
      # serviceId: microservice-user
      stripPrefix: false
      url: http://localhost:8081
    product-cart:
      path: /api/v1/cart/**
      serviceId: microservice-cart
      stripPrefix: false
    product-order:
      path: /api/v1/order/**
      serviceId: microservice-order
      stripPrefix: false
